### ISSUE TITLE
More Tokens

### ISSUE THREAD

**Issue by obe1342** [DaRealSh0T/Clone-Smasher#2]
Please allow us to add more tokens for multiple skins on agariohub

ex: 

`
{
	"botNames": [
		"Clone Smasher"
	],
	"account": "token1", "token2", "token3",
	"useProxyApi": true,
	"useAccount": false,
	"maxBots": 100
}`

**Comment by DaRealSh0T** [comment]
Done! https://github.com/DaRealSh0T/Clone-Smasher/commit/b1c084572ee1751397183752e89e5afd7cb6899b
