### ISSUE TITLE
Problems using another host

### ISSUE THREAD

**Issue by WebConForBFH** [DaRealSh0T/Clone-Smasher#5]
Hey,

Cellcraft is banning if it detects you using the botserver locally so I set up the server on my dedicated server, changed localhost to my IP but when I try to use the bots it leaves me with 4-5 bots (200 set) and these are also very laggy. Doesn´t matter if I use Proxy API or my own private SOCKS5. My server is powerful enough I guess (i7-3770k, 32GB RAM)

Any ideas?

**Comment by DaRealSh0T** [comment]
There shouldn't be any problems using other hosts. They might just have added new bot protection, i'm not sure.
