### ISSUE TITLE
How do I add a certificate for wss

### ISSUE THREAD

**Issue by 1-TB** [DaRealSh0T/Clone-Smasher#9]
I want to be able to host this on a server and connect to it remotely but the connection gets blocked because it's insecure (ws) not (wss). How might I go about adding a ssl certificate and use wss.

**Comment by DaRealSh0T** [comment]
Do you already have an SSL certificate created?

**Comment by OverallGod** [comment]
Yes

**Comment by 1-TB** [comment]
> Do you already have an SSL certificate created?

Yes

**Comment by 1-TB** [comment]
I just don’t know how I can use it with web sockets, I’m not very familiar with node js

**Comment by Rivet-archived** [comment]
@OverallGod Replace your `server.js` to:

```js
import WebSocket from 'ws';
import { scrapeProxys } from  "./modules/proxyManager.js"
import { Client } from  "./modules/userModule.js"
import config from './config.js';
import * as fs from 'fs';
import https from 'https';

console.log('Bots maintained by DaRealSh0T and keksbyte');

let httpsServer = https.createServer({
	key: fs.readFileSync('key.pem', 'utf8'), // Change this
	cert: fs.readFileSync('cert.pem', 'utf8') // And this
}).listen(3523);

const wss = new WebSocket.Server({
	server: httpsServer
});

function parsePT(pt) {
    var type = pt.toLowerCase();
    if (!['socks4', 'socks5', 'http'].includes(type))
        type = 'socks4';
    return type;
}
wss.on('listening', (ws) => {
    scrapeProxys(config.useProxyApi, parsePT(config.proxyType));
})
wss.on('connection', (ws, req) => {
	ws.Client = new Client(ws, req);
});

export function getConfig() {
    return config;
}
```

**Comment by 1-TB** [comment]
> @OverallGod Replace your `server.js` to:
> 
> 
> 
> ```js
> 
> import WebSocket from 'ws';
> 
> import { scrapeProxys } from  "./modules/proxyManager.js"
> 
> import { Client } from  "./modules/userModule.js"
> 
> import config from './config.js';
> 
> import * as fs from 'fs';
> 
> import https from 'https';
> 
> 
> 
> console.log('Bots maintained by DaRealSh0T and keksbyte');
> 
> 
> 
> let httpsServer = https.createServer({
> 
> 	key: fs.readFileSync('key.pem', 'utf8'), // Change this
> 
> 	cert: fs.readFileSync('cert.pem', 'utf8') // And this
> 
> }).listen(3523);
> 
> 
> 
> const wss = new WebSocket.Server({
> 
> 	server: httpsServer
> 
> });
> 
> 
> 
> function parsePT(pt) {
> 
>     var type = pt.toLowerCase();
> 
>     if (!['socks4', 'socks5', 'http'].includes(type))
> 
>         type = 'socks4';
> 
>     return type;
> 
> }
> 
> wss.on('listening', (ws) => {
> 
>     scrapeProxys(config.useProxyApi, parsePT(config.proxyType));
> 
> })
> 
> wss.on('connection', (ws, req) => {
> 
> 	ws.Client = new Client(ws, req);
> 
> });
> 
> 
> 
> export function getConfig() {
> 
>     return config;
> 
> }
> 
> ```

Didn't exactly work but I got it figured out, thank you!
